version: "3.7"

services:
  front-envoy:
    build:
      context: ./envoy
      dockerfile: ./Dockerfile
    volumes:
      - ./envoy:/etc/envoyfile
      - /srv/certs:/etc/certs # mount server certificates to etc
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "1883:1883"
      - "8001:8001"

  hivemq:
    container_name: hivemq
    image: hivemq/hivemq3
    networks:
      envoymesh:
        aliases:
          - hivemq
    ports:
      - "9080:8080"

networks:
  envoymesh: {}
