version: "3.7"

services:
  front-envoy:
    container_name: envoy_proxy-service
    build:
      context: ./envoy
      dockerfile: ./Dockerfile
    volumes:
      - ./envoy:/etc/envoyfile
      - /srv/certs:/etc/certs # mount server certificates to etc
    networks:
      - envoymesh
    expose: # ports are only exposed to internal services in the network
      - "80" 
      - "8001"
    ports:
      - "8000:80" # host:container
      #- "1883:1883"
      - "8883:8883"
      - "8001:8001"

  hivemq:
    container_name: hivemq
    image: hivemq/hivemq3
    networks:
      envoymesh:
        aliases:
          - hivemq
    ports:
      - "9080:8080"

networks:
  envoymesh: {}
